# Generated by Django 3.0.7 on 2020-06-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200611_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='picture',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
